version: '3.2'
services:
  crew-app:
    build: ../
    environment:
      - PORT=5000
  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - crew-app
    environment:
      - CYPRESS_baseUrl=http://crew-app:5000
    working_dir: /e2e
    build:
      context: .
      dockerfile: ./Dockerfile.cypress
    volumes:
      - ./:/e2e
